### ISSUE TITLE
Spacy Can't find model X

### ISSUE THREAD

**Issue by ygorg** [boudinfl/pke#113]
There are a lot of error concerning spacy not finding models.

`OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

A fix would be to catch the exception and add a message like (modifying `en` accordingly)
> Can't find model 'en'. You can link existing models to 'en' using `python3 -m spacy link existing_model en`.
> Or installing the model using `python3 -m spacy download en`

Maybe listing downloaded models to show what is possible.

**Comment by DefinitelyArnav** [comment]
Faced a similar issue a while back. I used `pip3 list` to see if the "en_core_web_sm" is present in the environment. It apparently was. The issue was that this "en_core_web_sm" module wasn't linked to "en". Thus I created a symlink manually and it worked.
To create a symlink manually use the command below:

`ln -s destination-file  target-file`
or specifically in this case, it would be
`ln -s path\to\en  path\to\en_core_web_sm
`

**Comment by ygorg** [comment]
Hi @DefinitelyArnav, to build up on this I recently found that `python3 -m spacy validate` gives valuable informations on what is installed and linked !
Also spacy provides a mechanism to link models without having to search the whereabouts:
`python3 -m spacy link en_core_web_sm  en`

**Comment by Stephan972** [comment]
As part of PKE install, I recently installed spacy english model. I got the following message: 

    ⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. 
      Please use the full pipeline package name 'en_core_web_sm' instead.

**Comment by ygorg** [comment]
Hi @Stephan972 , what was the command that triggered this warning ?
