### ISSUE TITLE
Any way to support Chinese? ('zh')

### ISSUE THREAD

**Issue by plourenco75** [boudinfl/pke#140]
Your docs page state you can support any language model support by Spacy. However, it seems anything outside of the list "ISO_to_language" will revert to 'en'.
Is there any way to use pke with Chinese?

**Comment by ygorg** [comment]
Hello,
Indeed as of right now, pke uses spacy to process raw text.

In order to use pke with any language, you can pre-tokenize and pre-pos-tag your text using any software and then create an XML file complying with CoreNLP format ([see here for an example](https://github.com/boudinfl/pke/blob/master/tests/data/1939.xml)).
If you are not able to POS-tag your files, filing the `<POS>` tag with the empty string and using the n-gram candidate selection should work.
If you want to train supervised methods, the reference keyphrases should be tokenized (there should be a space between every token).

**Comment by ygorg** [comment]
I just realised that `spacy` now supports chinese, so this is way easier !
Please install this branch of [`ygor/pke - fixes`](https://github.com/ygorg/pke/commits/fixes) by running: `python3 -m pip install https://github.com/ygorg/pke/archive/fixes.zip`.
Then install the chinese model of spacy : `python3 -m spacy install zh_core_web_sm`

You can now use `pke` as follows:
```python
import pke
import spacy

nlp =spacy.load('zh_core_web_sm')

e = pke.unsupervised.MultipartiteRank()
e.load_document(text, language='zh', spacy_model=nlp)
```

**Comment by plourenco75** [comment]
Thanks for that, it worked great for Chinese!

Another question? I would like to use this library for a use case that
requires many texts to be analysed sequentially. At the moment, if you load
up an array of texts to analyse and call pke, it's a very slow process
since the language models are being loaded each time.

Could you recommend a way to modify this library such that the language
models are loaded once for an array of texts to be analysed?

**Comment by ygorg** [comment]
Yes I'm kinda thinking of a way to process multiple documents at once (spacy supports batching, and introducing neural models will need batching support).
As of right now the `spacy_model` parameter was introduced for this purpose, so you can load your spacy model, keep it and pass it in the `load_document` function every time. The cacheing mechanism for resources could be improved (even for tf-idf, lda_models and such).

Something like:
```python
nlp = spacy.load('en_core_web_sm')
result = {}
for k, t in texts():
    e = pke.unsupervised.MultipartiteRank()
    e.load_document(t, spacy_model=nlp)
    e.candidate_selection()
    e.candidate_weighting()
    results[k] = e.get_n_best(n=10)
```

Closing this issue because we are getting off track :)

**Comment by JingxinLee** [comment]
> _Edit 08/01/2021 : To use chinese model just download the chinese spacy model and use the mode's name in PKE. No extra step needed._ I just realised that `spacy` now supports chinese, so this is way easier ! Please install this branch of [`ygor/pke - fixes`](https://github.com/ygorg/pke/commits/fixes) by running: `python3 -m pip install https://github.com/ygorg/pke/archive/fixes.zip`. Then install the chinese model of spacy : `python3 -m spacy install zh_core_web_sm`
> 
> You can now use `pke` as follows:
> 
> ```python
> import pke
> import spacy
> 
> nlp =spacy.load('zh_core_web_sm')
> 
> e = pke.unsupervised.MultipartiteRank()
> e.load_document(text, language='zh', spacy_model=nlp)
> ```

Maybe you mean "python3 -m spacy **download** zh_core_web_sm" ?
