### ISSUE TITLE
best model

### ISSUE THREAD

**Issue by kartikeyahl** [boudinfl/pke#154]
hey! I was wondering which model is proved to be best and why?

**Comment by ygorg** [comment]
Hi !

I don't quite know how to answer your question because every method is different and yields different sets of keyphrases.
In order to take a decision you can check [Hasan & Ng's 2014 survey](https://www.aclweb.org/anthology/P14-1119.pdf) (especially section 5) and our [large scale evaluation of models](https://arxiv.org/pdf/2003.04628.pdf).

Depending on the data available to you, you can check [CopyRNN](https://arxiv.org/pdf/1704.06879.pdf) (supervised neural network) or [Kea]() (supervised naive bayes), [YAKE](https://www.sciencedirect.com/science/article/pii/S0020025519308588?casa_token=mJAsKOswr58AAAAA:q6rnU4ltmLWpjLRbSqfwHftV5rn8FTXKxp3pYU6CMpUi16ILWD3M9HiSK9uiVXuxF1RDoiUs5Sk) or [MultipartiteRank](https://www.aclweb.org/anthology/N18-2105.pdf) (both unsupervised).

Good luck !
