### ISSUE TITLE
can't find it

### ISSUE THREAD

**Issue by cuczy** [boudinfl/pke#157]
I just realised that `spacy` now supports chinese, so this is way easier !
Please install this branch of [`ygor/pke - fixes`](https://github.com/ygorg/pke/commits/fixes) by running: `python3 -m pip install https://github.com/ygorg/pke/archive/fixes.zip`.
Then install the chinese model of spacy : `python3 -m spacy install zh_core_web_sm`

You can now use `pke` as follows:
```python
import pke
import spacy

nlp =spacy.load('zh_core_web_sm')

e = pke.unsupervised.MultipartiteRank()
e.load_document(text, language='zh', spacy_model=nlp)
```

_Originally posted by @ygorg in https://github.com/boudinfl/pke/issues/140#issuecomment-683752377_

**Comment by ygorg** [comment]
Hi, does this issue refers to #156 ?
If yes, then I guess you wanted to use the chinese model then ran into #140, and then read the last message stating that spacy now offers a chinese model. And pasted this message here ?

In the future, please write more explicit title issue and explain the problem you are facing, instead of creating multiple issues linked to the original problem which seem to be "How to use PKE to process chinese".
Have a nice day !
