### ISSUE TITLE
speed up with new graph library

### ISSUE THREAD

**Issue by shyambhu-mukherjee** [boudinfl/pke#168]
I see that we are using the networkx project for building the graph. But several graphs have much less memory prints and higher speed such as igraph. would love to know what the authors of this lib think about this.

**Comment by ygorg** [comment]
Hi, thanks for this suggestion.
If you are interested in this, you could set up an experiment to evaluate the speed and memory footprint of graph creation.
I think the test should include at least TextRank and MultipartiteRank, and be tested on ACM (long documents), WWW and KP20k (if not too long) because they have a lot of document (see [ake-datasets](https://github.com/boudinfl/ake-datasets)).
The time to load the 2 libraries might also be interested to report.
